---
- name: Install metric beat
  hosts: webservers
  become: true
  tasks:

  - name: Download ans install metricbeat
    apt:
      deb: "https://artifacts.elastic.co/downloads/beats/metricbeat/metricbeat-7.6.1-amd64.deb"
      state: present

  - name: drop in metricbeat config
    copy:
      src: /etc/ansible/metricbeat.cfg
      dest: /etc/metricbeat/metricbeat.yml

  - name: enable and configure docker module for metric beat
    command: metricbeat modules enable docker

  - name: setup metric beat
    command: metricbeat setup

  - name: enable service metricbeat on boot
    systemd:
      name: metricbeat
      enabled: yes
      state: started
